p8105_hw2_fm2751
================
2022-10-05

## Load useful libraries first!

``` r
library(tidyverse)
library(readxl)
library(lubridate)
```

# Problem 0

Public GitHub repo, local R Project, subdirectory for data, and .Rmd
file created and rendered to github_document.

# Problem 1

Read and clean the data, convert the entry variable from character (YES
vs NO) to a logical variable

``` r
trans_ent = 
  read_csv(
    "Data_hw2/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

-   Description of the dataset: the dataset contains retain lines and
    station names, their longitude and latitude, the routes they have,
    information about entry and entrance type, if they are exit only, if
    they have vending machine and if it is ADA compliant.
-   The process begins with data import, updates variable names, and
    selects the columns that will be used in later parts fo this
    problem. We update `entry` from `yes` / `no` to a logical variable.
-   These data are not tidy
-   dimension of the resulting dataset: 1868 rows and 20 columns.

``` r
trans_ent %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

-   there are 465 distinct stations.

``` r
trans_ent %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

-   84 stations are ADA compliant.

``` r
trans_ent %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

-   37.70% of station entrances / exits without vending allow entrance.

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

-   60 distinct stations serve the A train. Among stations that serve
    the A train, 17 many are ADA compliant.

# Problem 2

``` r
Mrtrashwheel = 
  read_excel(
    "Data_hw2/Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N550") %>% 
  janitor::clean_names() %>% 
  filter(dumpster != "NA") %>% 
  mutate(sports_balls = as.integer(round(sports_balls))) %>%
  mutate(prefix = "Mr") %>%
  mutate(year = as.numeric(year))

Mrtrashwheel
```

    ## # A tibble: 547 × 15
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 537 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, prefix <chr>, and abbreviated
    ## #   variable names ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

``` r
Proftrashwheel = 
  read_excel(
    "Data_hw2/Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:N97") %>% 
  janitor::clean_names() %>% 
  filter(dumpster != "NA") %>%
  mutate(prefix = "Prof") %>%
  mutate(year = as.numeric(year))

Proftrashwheel
```

    ## # A tibble: 94 × 15
    ##    dumpster month     year date                weight_…¹ volum…² plast…³ polys…⁴
    ##       <dbl> <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00      1.79      15    1950    6080
    ##  2        2 January   2017 2017-01-30 00:00:00      1.58      15    9540   11230
    ##  3        3 February  2017 2017-02-26 00:00:00      2.32      18    8350    9210
    ##  4        4 February  2017 2017-02-26 00:00:00      3.72      15    8590    1030
    ##  5        5 February  2017 2017-02-28 00:00:00      1.45      15    7830    9950
    ##  6        6 March     2017 2017-03-30 00:00:00      1.71      15    8210   10340
    ##  7        7 April     2017 2017-04-01 00:00:00      1.82      15    9830   11020
    ##  8        8 April     2017 2017-04-20 00:00:00      2.37      15    9240    8760
    ##  9        9 May       2017 2017-05-10 00:00:00      2.64      15    9540    8810
    ## 10       10 May       2017 2017-05-26 00:00:00      2.78      15    8230    7800
    ## # … with 84 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, x14 <lgl>, prefix <chr>, and abbreviated variable
    ## #   names ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles, ⁴​polystyrene

``` r
trash_complete = 
  full_join(Mrtrashwheel, Proftrashwheel, by = c("dumpster","month","year","date","weight_tons","volume_cubic_yards","plastic_bottles","polystyrene","cigarette_butts","glass_bottles", "grocery_bags", "chip_bags", "homes_powered","prefix"))

trash_complete
```

    ## # A tibble: 641 × 16
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 631 more rows, 8 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, prefix <chr>, x14 <lgl>, and
    ## #   abbreviated variable names ¹​volume_cubic_yards, ²​plastic_bottles,
    ## #   ³​polystyrene

``` r
trash_complete %>%
  filter(prefix == "Prof") %>%
  summarise(total_weight = sum(weight_tons))
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         190.

``` r
trash_complete %>%
  filter(prefix == "Mr" & year =="2020") %>%
  summarise(total_balls = sum(sports_balls))
```

    ## # A tibble: 1 × 1
    ##   total_balls
    ##         <int>
    ## 1         856

## Description:

There are 641 observations in the resulting dataset (named as
“trash_complete”). This dataset contains several key variables, for
example: weight of trash in tons, number of sports balls and date.

## Answer:

-   The total weight of trash collected by Professor Trash Wheel is 190
    tons.
-   The total number of sports balls collected by Mr. Trash Wheel in
    2020 is 856.

# Problem 3

``` r
pols_month = 
  read.csv("Data_hw2/fivethirtyeight_datasets/pols-month.csv") %>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = month.name[as.numeric(month)]) %>%
  pivot_longer(
    prez_gop | prez_dem,
    names_to = "president",
    names_prefix = "prez_",
    values_to = "gop_or_dem") %>%
  filter(gop_or_dem != 0) %>%
  select(!day & !gop_or_dem) %>%
  relocate(year, month, president, everything())
```

``` r
snp =
  read.csv("Data_hw2/fivethirtyeight_datasets/snp.csv") %>%
  mutate(date = mdy(date)) %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(year = ifelse(as.numeric(year)>2049, as.numeric(year)-100, year)) %>%
  mutate(month = month.name[as.numeric(month)]) %>%
  select(!day) %>%
  relocate(year, month, everything())
```

``` r
unemployment =
  read.csv("Data_hw2/fivethirtyeight_datasets/unemployment.csv") %>%
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment") %>%
  janitor::clean_names()
```

``` r
pols_month_snp =
  left_join(pols_month, snp, by = c("year", "month")) %>%
  mutate(year = as.numeric(year))
```

``` r
pol_snp_unemployment =
  left_join(pols_month_snp, unemployment, by = c("year", "month"))
```

``` r
range(pull(pol_snp_unemployment, var = 1))
```

    ## [1] 1947 2015

## Description:

The pol-month dataset contains 822 observations and 9 variavles. This
dataset contains key information variables like year, month and
president. The snp dataset contains 787 observations and 3 variavles,
they are year, month and close. The unemployment dataset contains 816
observations and 3 variables, they are year, month, unemployment. The
resulting dataset (named as “pol_snp_unemployment”) is a summary of the
above 3 datasets. It contains 822 observationa and 11 variables (822
rows × 11 columns). This dataset contains data from year 1947 to year
2015. Key variables include year, month, president, unemployment and
close. There are some missing values in this dataset due to incomplete
information.
